name : Greg Smith

markdown: kramdown

google_analytics: G-T1DHRSPMVZ

excerpt_separator: <!--more-->

permalink: /blog/:year/:month/:day/:title

# default front matter for static files
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
